name: 'CI/CD example'
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
  
  set-terraform:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
  
  Initialize:
    runs-on: ubuntu-latest

    needs: set-terraform

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Initialize
      run: terraform init
